# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-07 23:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'required': 'Username is required.'}, max_length=50, verbose_name='Name')),
                ('birthday', models.DateField(error_messages={'required': 'Birthday is required.'}, verbose_name='Birthday')),
                ('random_number', models.IntegerField(error_messages={'max_value': 'The value should be less than 100.', 'min_value': 'The value should be greater than 0.', 'required': 'Random number is required.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Random Number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
